Dropping a teaser shows no placeholder
adobe/aem-site-template-standard pull request #86
Opened 2022-03-21 08:17 UTC by comanV

Fixes #85.
Currently, the main CSS of the Teaser Component from the Standard Site Template provides white text color for pretitle, title, description and link and also some positioning transformation . This is working as expected if the author configures an asset, otherwise the blue border of a new component added in the Page Editor will not be properly displayed. Also, the placeholder and the other defined text of the Teaser will not be visible, they will be rendered white on white when a Teaser Component is dropped on a page.
This PR provides CSS for styling the teasers that don't have an asset configured, to be properly displayed in Page Editor and to have pretitle, title, description and title link rendered in black text color.
<img width="1465" alt="Screenshot 2022-03-21 at 08 25 38" src="https://user-images.githubusercontent.com/79856745/159224239-a91251f4-ddba-43c7-8261-4231da77fc7f.png">
<img width="1101" alt="Screenshot 2022-03-20 at 22 40 01" src="https://user-images.githubusercontent.com/79856745/159224682-fef0976f-bc62-4ea4-a859-e1fb4e137b13.png">

2022-03-21 12:52 UTC, msagolj approved these changes

2022-03-21 13:38 UTC, jckautzmann commented
Instead of having the javascript directly update the CSS style properties, couldn't it add a class (e.g. `cmp-teaser__noimage`) which is styled in a CSS file?

2022-03-21 16:26 UTC, vladbailescu requested changes
I think this kind of client-side processing is not really needed, we could always target `cmp-teaser__content:only-child` and its children for missing images.

2022-03-21 16:31 UTC, vladbailescu commented on theme/src/components/teaser/_teaser.scss
> +    color: #000000;
I'd rather we use the variable defined at https://github.com/adobe/aem-site-template-standard/blob/main/theme/src/site/_variables.scss#L27

2022-03-22 06:58 UTC, vladbailescu approved these changes

2022-03-23 09:05 UTC, merged